services:
  tf:
    image: hashicorp/terraform:1.13.3
    volumes:
      - ./setup:/tf-code/setup
      - ./deploy:/tf-code/deploy
      # Mount your ~/.aws credentials
      - ~/.aws:/root/.aws:ro
      # - ~/.ssh:/root/.ssh:ro
    working_dir: /tf-code
    environment:
      # The :- operator tells Compose: If the variable isn't set, use an empty string quietly.
      # hence, no warning like:
      # WARN[0000] The "TF_WORKSPACE" variable is not set. Defaulting to a blank string.
      - TF_WORKSPACE=${TF_WORKSPACE:-}
